all: notstack4easier.out notstack4harder.out

notstack4easier.out: notstack4easier.c
	gcc notstack4easier.c -no-pie -o notstack4easier.out

notstack4harder.out: notstack4harder.c
	gcc notstack4harder.c -no-pie -o notstack4harder.out